// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgfeahwvbhbcuulfriur.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnZmVhaHd2YmhiY3V1bGZyaXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyMTc3MTUsImV4cCI6MjA3NTc5MzcxNX0.6PPzgLFGp9k7vQn-fMzyzykllDw2xgjdJs0I-lTEQq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});